Added multiple template support; moved LICENSE
Template files are now specified as the first comment at the top of each
HTML file. The example folder shows how multiple templates may be used.

If you are an existing user, you MUST add the name of the template you
use to the top of each HTML file you are templating before updating
web-tools. Otherwise, you will likely experience breakage when trying to
use these scripts.

Additionally, LICENSE was moved to LICENSE.md

diff --git a/mkpost b/mkpost
--- a/mkpost
+++ b/mkpost
@@ -26,7 +26,23 @@ if [ -f "$FILENAME" ]; then
   esac
 fi
 
-echo "<h2>$(./encode_text "$TITLE")</h2>" > "$FILENAME"
+printf 'Enter template name: '
+read TEMPLATE
+echo
+
+if [ -z "$TEMPLATE" ]; then
+  TEMPLATE="base"
+  printf 'No template supplied, defaulting to "base"'
+fi
+
+[[ -f "templates/${TEMPLATE}_testing.html" ]]
+  && printf "Could not find testing variant for \"$TEMPLATE\"" > &2
+
+[[ -f "templates/${TEMPLATE}_production.html" ]]
+  && printf "Could not find production variant for \"$TEMPLATE\"" > &2
+
+echo "<!-- $TEMPLATE -->" > "$FILENAME"
+echo "<h2>$(./encode_text "$TITLE")</h2>" >> "$FILENAME"
 
 printf "Post \"$TITLE\" created, edit post? [Y/n] "
 read EDIT_CONFIRM
